language: node_js
node_js:
  - "6.3"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  - CXX=g++-4.8
before_install:
  - openssl aes-256-cbc -K $encrypted_1645300b04d0_key -iv $encrypted_1645300b04d0_iv -in config/aws.json.travis.enc -out config/aws.json -d
  - cp config/test.js.example config/test.js
